[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
name = "root"
version = "0.0.0"
description = ""

[tool.poetry.dependencies]
pandas = "*"
python = ">=3.10,<4.0"
seaborn = "*"
matplotlib = "*"
